function fh = figure()
THETA0LIM	= [-15,50];
RLIM		= [1E0,1E10];
MLIM		= [1E0,1E9];
DTHETALIM	= [0,40];


% axes
AX.radius = lib.module.figure.axes(...
	'x','$\theta_0$',...
	'y','$r/r_c$',...
	'axes', {...
		'XLim',		THETA0LIM, ...
		'YLim',		RLIM,...
		'YTick',	10.^(0:2:10),...
		'YScale',	'log' ...
	}...
);

AX.mass = lib.module.figure.axes(...
	'x', '$\theta_0$',...
	'y', '$M(r)/M_c$',...
	'axes',	{...
		'XLim',		THETA0LIM, ...
		'YLim',		MLIM,...
		'YTick',	10.^(0:2:8),...
		'YScale',	'log' ...
	}...
);

AX.degeneracy = lib.module.figure.axes(...
	'x','$\theta_0$',...
	'y','$\theta_0 - \theta(r)$',...
	'axes',{...
		'XLim',		THETA0LIM, ...
		'YLim',		DTHETALIM,...
		'YTick',	0:5:35 ...
	}...
);

% figure
ax = [AX.degeneracy;AX.mass;AX.radius];
fh = lib.module.sapthesis.figure_grid(ax,'axHeight',4.5);