function fh = figure
AXIS.center	= lib.require(@lib.model.tov.rar.axes.center);
AXIS.core	= lib.require(@lib.model.tov.rar.axes.core);

AR			= AXIS.core.radius;
ARHO		= AXIS.center.density;
AV			= AXIS.core.velocity;
AM			= AXIS.core.mass;

AX.radius = {...
	'XLim',			[1E-5,1E10],...
	'XTick',		10.^(-4:4:9),...
	'XScale',		'log' ...
};

AX.density = {...
	'YLim',			[1E-30,1E1],...
	'YTick',		10.^(-28:7:0),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.velocity = {...
	'YLim',			[2E-5,2],...
	'YTick',		10.^(-5:1:0),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.mass = {...
	'YLim',			[1E-4,1E10],...
	'YTick',		10.^(-3:3:9),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

for ii=1:3
	ax(3,ii) = lib.module.figure.axes('x',AR, 'y',ARHO,	'axes',[AX.radius,AX.density]);
	ax(2,ii) = lib.module.figure.axes('x',AR, 'y',AV,	'axes',[AX.radius,AX.velocity]);
	ax(1,ii) = lib.module.figure.axes('x',AR, 'y',AM,	'axes',[AX.radius,AX.mass]);
end

fh = lib.module.sapthesis.figure_grid(ax,'axHeight','equal');