EXPORT.radius = lib.module.ProfileMapping(...
	@(obj) obj.data.radius,...
	'r' ...
);

EXPORT.mass = lib.module.ProfileMapping(...
	@(obj) ones(size(obj.data.radius)),...
	'M(r)'...
);

EXPORT.velocity = lib.module.ProfileMapping(...
	@(obj) sqrt(1./obj.data.radius),...
	'v(r)'...
);