ANCH = lib.require(@model.tov.fd.anchor);

EXPORT.radius =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_core.map(obj,Y),...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	0.1,...
	0.2,...
	1 ...
);

EXPORT.potential =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	@(obj,Y) ANCH.center.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.density =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	@(obj,Y) ANCH.center.map(obj,Y),...
	0.3,...
	0,...
	1 ...
);

EXPORT.density_critical =  module.ProfileClip(...
	@(obj,Y) -max(findpeaks(-obj.get('density')./obj.get('densityCritical'))),...
	@(obj,Y) max(obj.get('density')./obj.get('densityCritical')),...
	0,...
	0,...
	1 ...
);

EXPORT.pressure =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	@(obj,Y) ANCH.center.map(obj,Y),...
	0.3,...
	0,...
	1 ...
);

% EXPORT.phasespace =  module.ProfileClip(...
% 	@(obj,Y) interp1(obj.radius,obj.phasespace,fhalo(obj)),...
% 	@(obj,Y) mean(obj.phasespace(1:10)),...
% 	0,...
% 	0,...
% 	1 ...
% );

EXPORT.velocity =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_plateau.map(obj,Y),...
	@(obj,Y) ANCH.velocity_core.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.velocityRMS =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	@(obj,Y) ANCH.center.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.mass =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_core.map(obj,Y),...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.massDiff =  module.ProfileClip(...
	@(obj,Y) ANCH.mass_plateau.map(obj,Y),...
	@(obj,Y) ANCH.mass_core.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.potential =  module.ProfileClip(...
	@(obj,Y) ANCH.center.map(obj,Y),...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.potentialDiff =  module.ProfileClip(...
	@(obj,Y) -max(findpeaks(-Y)),...
	@(obj,Y) max(findpeaks(Y)),...
	0,...
	0,...
	1 ...
);

EXPORT.degeneracy =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	@(obj,Y) ANCH.center.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.degeneracyDiff =  module.ProfileClip(...
	@(obj,Y) ANCH.degeneracy_plateau.map(obj,Y),...
	@(obj,Y) ANCH.degeneracy_core.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.cutoff =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	@(obj,Y) ANCH.center.map(obj,Y),...
	0,...
	0,...
	1 ...
);

EXPORT.temperature =  module.ProfileClip(...
	@(obj,Y) ANCH.velocity_halo.map(obj,Y),...
	@(obj,Y) ANCH.center.map(obj,Y),...
	0.2,...
	0,...
	1 ...
);

EXPORT.temperatureDiff =  module.ProfileClip(...
	@(obj,Y) max(findpeaks(Y)),...
	@(obj,Y) -max(findpeaks(-Y)),...
	0,...
	0,...
	1 ...
);

EXPORT.schwarzschild =  module.ProfileClip(...
	@(obj,Y) ANCH.schwarzschild_core.map(obj,Y),...
	@(obj,Y) ANCH.schwarzschild_plateau.map(obj,Y),...
	0,...
	0,...
	1 ...
);