ANCH	= lib.require(@model.tov.fd.anchor);
MAP		= lib.require(@model.tov.fd.map);

% EXPORT.degeneracy_plateau_offset = module.ProfileMapping(...
% 	@(obj) MAP.degeneracy.map(obj) - ANCH.degeneracy_plateau.map(obj,MAP.degeneracy),...
% 	'\theta(r) - \theta_p'...
% );

EXPORT.degeneracy_plateau_offset = module.ProfileMapping(...
	@(obj) MAP.degeneracy.map(obj) - ANCH.velocity_plateau.map(obj,MAP.degeneracy),...
	'\theta(r) - \theta_p'...
);