EXPORT.radius = lib.module.ProfileMapping(...
	@(obj) obj.data.radius,...
	'r' ...
);

EXPORT.mass = lib.module.ProfileMapping(...
	@(obj) obj.data.mass,...
	'M(r)'...
);

EXPORT.velocity = lib.module.ProfileMapping(...
	@(obj) obj.data.velocity,...
	'v(r)'...
);