function fh = figure
BETA0LIM	= [1E-8,1E2];
RLIM		= [1E0,1E10];
MLIM		= [1E0,1E9];
DTHETALIM	= [-5,85];

% axes
AX.radius = {...
	'xlabel','$\beta_0$',...
	'ylabel','$r/r_c$',...
	'axes', {...
		'XLim',		BETA0LIM, ...
		'YLim',		RLIM,...
		'XTick',	10.^(-7:2:1),...
		'YTick',	10.^(0:2:10),...
		'XScale',	'log',...
		'YScale',	'log' ...
	}...
};

AX.mass = {...
	'xlabel', '$\beta_0$',...
	'ylabel', '$M(r)/M_c$',...
	'axes',	{...
		'XLim',		BETA0LIM, ...
		'YLim',		MLIM,...
		'XTick',	10.^(-7:2:1),...
		'YTick',	10.^(0:2:8),...
		'XScale',	'log',...
		'YScale',	'log' ...
	}...
};

AX.degeneracy = {...
	'xlabel','$\beta_0$',...
	'ylabel','$\theta_0 - \theta(r)$',...
	'axes',{...
		'XLim',		BETA0LIM, ...
		'YLim',		DTHETALIM,...
		'XTick',	10.^(-7:2:1),...
		'YTick',	-15:15:80,...
		'XScale',	'log' ...
	}...
};


for ii=1:3
	ax(:,ii) = [
		model.tov.rar.figure.ax(AX.degeneracy{:})
		model.tov.rar.figure.ax(AX.mass{:})
		model.tov.rar.figure.ax(AX.radius{:})
	];
end

fh = module.sapthesis.figure_grid(ax,'axHeight','equal','figure',{'FileName','analysis-beta0'});