function fh = figure
AXIS.center	= lib.require(@model.tov.rar.axes.center);
AXIS.core	= lib.require(@model.tov.rar.axes.core);
AXIS.plat	= lib.require(@model.tov.rar.axes.plateau);

AXLABEL.radius = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.plat.radius.mapmodel,...
	'scalemodel',	AXIS.plat.radius.scalemodel ...
);

AXLABEL.density = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.plat.density.mapmodel,...
	'scalemodel',	AXIS.plat.density.scalemodel ...
);

AXLABEL.velocity = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.plat.velocity.mapmodel,...
	'scalemodel',	AXIS.plat.velocity.scalemodel ...
);

AXLABEL.mass = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.plat.mass.mapmodel,...
	'scalemodel',	AXIS.plat.mass.scalemodel ...
);

AX.radius = {...
	'XLim',			[1E-6,1E7],...
	'XTick',		10.^(-8:2:9),...
	'XScale',		'log' ...
};

AX.density = {...
	'YLim',			[1E-15,1E15],...
	'YTick',		10.^(-16:4:16),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.velocity = {...
	'YLim',			[2E-1,5E1],...
	'YTick',		[0.5 1 2 5 10 20],...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.mass = {...
	'YLim',			[1E-12,1E7],...
	'YTick',		10.^(-9:4:5),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

for ii=1:2
	ax(3,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.density,	'axes', [AX.radius,AX.density]);
	ax(2,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.velocity,	'axes', [AX.radius,AX.velocity]);
	ax(1,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.mass,		'axes', [AX.radius,AX.mass]);
end

fh = module.sapthesis.figure_grid(ax,'axHeight',@(w) w*3/4,'figure',{'FileName','profiles'});