function main
P			= load('export/CacheProfileBeta0.mat');
STYLE		= lib.require(@configs.style_profiles);
AXIS.plat	= lib.require(@model.tov.rar.axes.plateau);
fh			= view.with_cutoff.beta0.profiles_weak.figure();

% makeup
for ii = 1:P.cored.low.length
	P.cored.low.data{ii}.data.density(end) = realmin;
end
for ii = 1:P.cored.high.length
	P.cored.high.data{ii}.data.density(end) = realmin;
end

% show figure
figure(fh);

% density
axes(fh.UserData.axes(3,1));
P.cored.low.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.density,...
	'plot', STYLE.low ...
));
P.cored.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.density,...
	'plot', STYLE.fd ...
));
title('low temperature')

axes(fh.UserData.axes(3,2));
P.cored.high.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.density,...
	'plot', STYLE.high ...
));
P.cored.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.density,...
	'plot', STYLE.fd ...
));
title('high temperature')


% velocity
axes(fh.UserData.axes(2,1));
P.cored.low.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.velocity,...
	'plot', STYLE.low ...
));
P.cored.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.velocity,...
	'plot', STYLE.fd ...
));

axes(fh.UserData.axes(2,2));
P.cored.high.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.velocity,...
	'plot', STYLE.high ...
));
P.cored.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.velocity,...
	'plot', STYLE.fd ...
));


% mass
axes(fh.UserData.axes(1,1));
P.cored.low.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.mass,...
	'plot', STYLE.low ...
));
P.cored.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.mass,...
	'plot', STYLE.fd ...
));

axes(fh.UserData.axes(1,2));
P.cored.high.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.mass,...
	'plot', STYLE.high ...
));
P.cored.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.mass,...
	'plot', STYLE.fd ...
));

% save pdf
lib.view.file.figure(fh,'export/beta0-weak');