function fh = figure
AXIS	= lib.require(@lib.model.tov.rar.axes.halo);

AR			= AXIS.radius;
ARHO		= AXIS.density;
AV			= AXIS.velocity;
AM			= AXIS.mass;

AX.radius = {...
	'XLim',		[1E-8,1E4],...
	'XTick',	10.^(-8:2:8),...
	'XScale',	'log' ...
};

AX.density = {...
	'YLim',		[1E-8,1E22],...
	'YTick',	10.^(-6:4:22),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.velocity = {...
	'YLim',		[2E-3,2E1],...
	'YTick',	10.^(-2:1:1),...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.mass = {...
	'YLim',		[1E-8,1E4],...
	'YTick',	10.^(-6:3:6),...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

for ii=1:1
	ax(3,ii) = lib.module.figure.axes('x',AR, 'y',ARHO,	'axes',[AX.radius,AX.density]);
	ax(2,ii) = lib.module.figure.axes('x',AR, 'y',AV,	'axes',[AX.radius,AX.velocity]);
	ax(1,ii) = lib.module.figure.axes('x',AR, 'y',AM,	'axes',[AX.radius,AX.mass]);
end

fh = lib.module.sapthesis.figure_grid(ax,'axHeight',6);

% link all x axes
linkaxes(ax,'x')
