function fh = figure
AXIS	= lib.require(@model.tov.rar.axes.halo);

AR			= AXIS.radius;
ARHO		= AXIS.density;
AV			= AXIS.velocity;
AM			= AXIS.mass;


AXLABEL.radius = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AR.mapmodel,...
	'scalemodel',	AR.scalemodel ...
);

AXLABEL.density = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		ARHO.mapmodel,...
	'scalemodel',	ARHO.scalemodel ...
);

AXLABEL.velocity = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AV.mapmodel,...
	'scalemodel',	AV.scalemodel ...
);

AXLABEL.mass = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AM.mapmodel,...
	'scalemodel',	AM.scalemodel ...
);


AX.radius = {...
	'XLim',		[1E-8,1E4],...
	'XTick',	10.^(-8:2:8),...
	'XScale',	'log' ...
};

AX.density = {...
	'YLim',		[1E-8,1E22],...
	'YTick',	10.^(-6:4:22),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.velocity = {...
	'YLim',		[2E-3,2E1],...
	'YTick',	10.^(-2:1:1),...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.mass = {...
	'YLim',		[1E-8,1E4],...
	'YTick',	10.^(-6:3:6),...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

for ii=1:1
	ax(3,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.density,'axes',[AX.radius,AX.density]);
	ax(2,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.velocity,'axes',[AX.radius,AX.velocity]);
	ax(1,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.mass,'axes',[AX.radius,AX.mass]);
end

fh = module.sapthesis.figure_grid(ax,'axHeight',6,'figure',{'FileName','profiles-halo'});

% link all x axes
linkaxes(ax,'x')
