function main
P			= load('export/CacheProfileTheta0Low.mat');
STYLE		= lib.require(@configs.style_profiles);
ANCH		= lib.require(@lib.model.tov.rar.anchor);
AXIS.core	= lib.require(@lib.model.tov.rar.axes.core);
AXIS.halo	= lib.require(@lib.model.tov.rar.axes.halo);
fh			= view.without_cutoff.theta0.profiles_halo.figure();

figure(fh);

% density
axes(fh.UserData.axes(3,1));
vline(1,1);

hg.is = hggroup(STYLE.isgroup{:});
plot([realmin,ANCH.center.map(P.is,AXIS.core.radius)],[1,1]*ANCH.center.map(P.is,AXIS.core.density),STYLE.is{:},'Parent',hg.is);
lib.view.plot.curve2D(...
	'data', P.is,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.density,...
	'plot',	[STYLE.is,{'Parent',hg.is}]...
);

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p)lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.halo.radius,...
	'y',	AXIS.halo.density,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));

lib.view.plot.legend([],'location','northeast');


% velocity
axes(fh.UserData.axes(2,1));
vline(1,1);

lib.view.plot.curve2D(...
	'data', P.is,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot',	[STYLE.is,STYLE.isgroup]...
);

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.halo.radius,...
	'y',	AXIS.halo.velocity,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));


% mass
axes(fh.UserData.axes(1,1));
vline(1,1);
lib.view.plot.curve2D(...
	'data', P.is,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot',	[STYLE.is,STYLE.isgroup]...
);

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.halo.radius,...
	'y',	AXIS.halo.mass,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));


% save
lib.view.latex.figure(...
	'path',		'export/without-cutoff/theta0-profiles-halo/',...
	'figure',	fh,...
	'label',	'fig:profiles:without-cutoff:central-degeneracy:halo',...
	'caption',	fileread('+view/+without_cutoff/+theta0/+profiles_halo/caption.txt') ...
);

function vline(x,y,varargin)
lib.view.plot.vline(x,'Color', [1 1 1]*0.7, 'LineStyle',':',varargin{:});
plot(x,y,'Marker','o', 'MarkerFaceColor', 'w', 'MarkerEdgeColor','w','MarkerSize',10);