function varargout = findSolutionCuspy(varargin)
searchCfg = lib.require(@configs.solutionSearchConfig);

Q = lib.module.struct(...
	'nlinfit',			{},...
	'gosect',			{},...
	'ResponseList',		searchCfg.ResponseList,...
	varargin{:}...
);

% set nlinfit options (for autofind)
opts				= statset('nlinfit');
opts.FunValCheck	= 'off';
opts.MaxIter		= 50;
opts.TolX			= 1E-12;

fSolution{1} = @(vm,list) script.nlinfit.theta0(...
	'model',	lib.struct.setfield(vm,'param/theta0',1.002*vm.param.theta0),...
	'list',		list,...
	'nlinfit',	{'options', opts, Q.nlinfit{:}} ...
);

[varargout{1:nargout}] = lib.module.find(...
	'query',		Q.query,...
	'ResponseList',	Q.ResponseList,...
	'model',		Q.model,...
	'fSolution',	fSolution ...
);

