function fh = figure
AXIS.center	= lib.require(@lib.model.tov.rar.axes.center);
AXIS.core	= lib.require(@lib.model.tov.rar.axes.core);

AR			= AXIS.core.radius;
ARHO		= AXIS.center.density;
AV			= AXIS.core.velocity;
AM			= AXIS.core.mass;

AX.radius = {...
	'XLim',			[1E-2,1E6],...
	'XTick',		10.^(-1:2:5),...
	'XScale',		'log' ...
};

AX.density = {...
	'YLim',			[1E-21,1E1],...
	'YTick',		10.^(-20:4:0),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.velocity = {...
	'YLim',			[2E-3,3E0],...
	'YTick',		10.^(-2:1:0),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.mass = {...
	'YLim',			[1E-5,1E7],...
	'YTick',		10.^(-4:2:6),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

for ii=1:2
	ax(3,ii) = lib.module.figure.axes('x',AR, 'y',ARHO,	'axes',[AX.radius,AX.density]);
	ax(2,ii) = lib.module.figure.axes('x',AR, 'y',AV,	'axes',[AX.radius,AX.velocity]);
	ax(1,ii) = lib.module.figure.axes('x',AR, 'y',AM,	'axes',[AX.radius,AX.mass]);
end

fh = lib.module.sapthesis.figure_grid(ax,'axHeight',@(w) w*3/4);