function fh = figure
AXIS.center	= lib.require(@model.tov.rar.axes.center);
AXIS.core	= lib.require(@model.tov.rar.axes.core);
AXIS.plat	= lib.require(@model.tov.rar.axes.plateau);

AXLABEL.radius = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.core.radius.mapmodel,...
	'scalemodel',	AXIS.core.radius.scalemodel ...
);

AXLABEL.density = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.center.density.mapmodel,...
	'scalemodel',	AXIS.center.density.scalemodel ...
);

AXLABEL.velocity = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.core.velocity.mapmodel,...
	'scalemodel',	AXIS.core.velocity.scalemodel ...
);

AXLABEL.mass = struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.core.mass.mapmodel,...
	'scalemodel',	AXIS.core.mass.scalemodel ...
);

AX.radius = {...
	'XLim',			[1E-2,1E6],...
	'XTick',		10.^(-1:2:5),...
	'XScale',		'log' ...
};

AX.density = {...
	'YLim',			[1E-21,1E1],...
	'YTick',		10.^(-20:4:0),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.velocity = {...
	'YLim',			[2E-3,3E0],...
	'YTick',		10.^(-2:1:0),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

AX.mass = {...
	'YLim',			[1E-5,1E7],...
	'YTick',		10.^(-4:2:6),...
	'YScale',		'log',...
	'YMinorTick',	'off' ...
};

for ii=1:3
	ax(3,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.density,	'axes', [AX.radius,AX.density]);
	ax(2,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.velocity,	'axes', [AX.radius,AX.velocity]);
	ax(1,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.mass,		'axes', [AX.radius,AX.mass]);
end

fh = module.sapthesis.figure_grid(ax,'axHeight','equal','figure',{'FileName','profiles'});