function main
P			= load('export/CacheProfileBeta0.mat');
STYLE		= lib.require(@configs.style_profiles);
AXIS.center	= lib.require(@model.tov.rar.axes.center);
AXIS.core	= lib.require(@model.tov.rar.axes.core);
fh			= view.with_cutoff.beta0.profiles_intermediate.figure();

% makeup
for ii = 1:P.cuspy.low.length
	P.cuspy.low.data{ii}.data.density(end) = realmin;
end
for ii = 1:P.cuspy.trans.length
	P.cuspy.trans.data{ii}.data.density(end) = realmin;
end
for ii = 1:P.cuspy.deficit.length
	P.cuspy.deficit.data{ii}.data.density(end) = realmin;
end
for ii = 1:P.cuspy.high.length
	P.cuspy.high.data{ii}.data.density(end) = realmin;
end

% show figure
figure(fh);

% density
axes(fh.UserData.axes(3,1));
P.cuspy.low.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', STYLE.cold ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', STYLE.fd ...
));
title('cold')

axes(fh.UserData.axes(3,2));
P.cuspy.deficit.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', STYLE.deficit ...
));
P.cuspy.trans.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', STYLE.trans2 ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', STYLE.fd ...
));
title('moderate')

axes(fh.UserData.axes(3,3));
P.cuspy.high.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', STYLE.hot ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', STYLE.fd ...
));
title('hot')


% velocity
axes(fh.UserData.axes(2,1));
P.cuspy.low.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot', STYLE.cold ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot', STYLE.fd ...
));

axes(fh.UserData.axes(2,2));
P.cuspy.deficit.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot', STYLE.deficit ...
));
P.cuspy.trans.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot', STYLE.trans2 ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot', STYLE.fd ...
));

axes(fh.UserData.axes(2,3));
P.cuspy.high.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot', STYLE.hot ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot', STYLE.fd ...
));


% mass
axes(fh.UserData.axes(1,1));
P.cuspy.low.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot', STYLE.cold ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot', STYLE.fd ...
));

axes(fh.UserData.axes(1,2));
P.cuspy.deficit.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot', STYLE.deficit ...
));
P.cuspy.trans.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot', STYLE.trans2 ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot', STYLE.fd ...
));

axes(fh.UserData.axes(1,3));
P.cuspy.high.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot', STYLE.hot ...
));
P.cuspy.low.pick(1).forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot', STYLE.fd ...
));

% save
lib.view.latex.figure(...
	'path',		'export/with-cutoff/beta0-intermediate-profile-core/',...
	'figure',	fh,...
	'label',	'fig:profile:with-cutoff:beta0-intermediate:core',...
	'caption',	fileread('+view/+with_cutoff/+beta0/+profiles_intermediate/caption.txt') ...
);