function fh = figure
THETA0LIM	= [-15,80];
RLIM		= [1E0,1E10];
MLIM		= [1E0,1E9];
DTHETALIM	= [-5,85];

% axes
AX.radius = {...
	'xlabel','$\theta_0$',...
	'ylabel','$r/r_c$',...
	'axes', {...
		'XLim',		THETA0LIM, ...
		'YLim',		RLIM,...
		'YScale',	'log'...
		'XTick',	-10:20:70,...
		'YTick',	10.^(0:2:10) ...
	}...
};

AX.mass = {...
	'xlabel', '$\theta_0$',...
	'ylabel', '$M(r)/M_c$',...
	'axes',	{...
		'XLim',		THETA0LIM, ...
		'YLim',		MLIM,...
		'YScale',	'log'...
		'XTick',	-10:20:70,...
		'YTick',	10.^(0:2:8) ...
	}...
};

AX.degeneracy = {...
	'xlabel','$\theta_0$',...
	'ylabel','$\theta_0 - \theta(r)$',...
	'axes',{...
		'XLim',		THETA0LIM, ...
		'YLim',		DTHETALIM,...
		'XTick',	-10:20:70,...
		'YTick',	-15:15:80 ...
	}...
};


for ii=1:3
	ax(:,ii) = [
		lib.module.figure.axes(AX.degeneracy{:})
		lib.module.figure.axes(AX.mass{:})
		lib.module.figure.axes(AX.radius{:})
	];
end

fh = lib.module.sapthesis.figure_grid(ax,'axHeight',@(w) w);