function varargout = W0_beta0(vm,list,varargin)
% set iteration print function
sPrec	= '%1.15e';
sStrong = ['<strong>' sPrec '</strong>'];
sFormat = strjoin({sStrong,sPrec,sStrong,'%1.3e\n'},'\t');
fLog	= @(SOL) fprintf(sFormat,SOL.data.beta0,SOL.data.theta0,SOL.data.W0,list.chi2(SOL));

% set vector function
fVector = @(vm) [
	vm.param.W0
	vm.param.beta0
];


% set update function
fUpdate = @(b,vm) struct(...
	'param', struct(...
		'beta0',	b(2),...
		'theta0',	vm.param.beta0,...
		'W0',		b(1) ...
	),...
	'options',	vm.options ...
);

% seach for solution
[varargout{1:nargout}] = model.tov.rar.nlinfit(vm,list,...
	'fVector',		fVector,...
	'fUpdate',		fUpdate,...
	'fLog',			fLog,...
	varargin{:} ...
);