C = lib.color.lines(20);

% degeneracy families
EXPORT.fdg = {...
	'Color',		C{2},...
	'LineWidth',	1.5 ...
};

EXPORT.fdggroup = {'DisplayName', 'fully degenerate core'};

EXPORT.is = {...
	'Color',		C{1},...
	'LineWidth',	1.5 ...
};

EXPORT.isgroup = {'DisplayName', 'isothermal sphere (IS)'};

EXPORT.fd = {...
	'Color',		'k' ...
};

EXPORT.fdgroup = {'DisplayName', 'RAR solutions (semi-degenerate)'};

EXPORT.trans = {...
	'Color',		C{6} ...
};

EXPORT.transgroup = {'DisplayName', 'RAR solutions (transition)'};

EXPORT.trans2 = {...
	'Color',		C{5} ...
};


% halo morphology
EXPORT.cored = {...
	'Color',		[1 1 1]*0.5 ...
};

EXPORT.cuspy = {...
	'Color',		C{5} ...
};

EXPORT.deficit = {...
	'Color',		C{4} ...
};

EXPORT.disrupt = {...
	'Color',		C{2} ...
};


% temperature families (cold, intermediate, hot)
EXPORT.coldGroup = {'DisplayName', 'RAR solutions (cold)'};

EXPORT.cold = {...
	'Color',		[0 0 0] ...
};

EXPORT.interGroup = {'DisplayName', 'RAR solutions (intermediate)'};

EXPORT.inter = {...
	'Color',		C{3} ...
};

EXPORT.hotGroup = {'DisplayName', 'RAR solutions (hot)'};

EXPORT.hot = {...
	'Color',		C{2} ...
};