function fh=figure(ax,varargin)


PADDING		= struct('top', 0.5, 'left', 1.5, 'right', 1.5, 'bottom', 1.5);
WIDTH		= 17;
ROWHEIGHT	= (WIDTH - PADDING.left - PADDING.right)*1/size(ax,2);

DIM = struct(...
	'width',	WIDTH,...
	'height',	ROWHEIGHT*size(ax,1) + PADDING.top + PADDING.bottom,...
	'padding',	PADDING,...
	'grid',		size(ax) ...
);

fh = figure(...
	'Visible',					'off',...
	'defaulttextinterpreter',	'latex',...
	'Units',					'centimeters',...
	'PaperUnits',				'centimeters',...
	'PaperSize',				[DIM.width DIM.height],...
	'PaperPosition',			[0,0,DIM.width,DIM.height],...
	varargin{:}...
);

fh.Position(2) = fh.Position(2) - (DIM.height - fh.Position(4));
fh.Position(3) = DIM.width;
fh.Position(4) = DIM.height;

AXWIDTH		= (DIM.width - (DIM.padding.left + DIM.padding.right))/DIM.grid(2);
AXHEIGHT	= (DIM.height - (DIM.padding.bottom + DIM.padding.top))/DIM.grid(1);


% link all x axes
linkaxes(ax,'x')

% hide ticks and labels
set(ax(2:3,:),'YTickLabel',[]);
set(ax(2:3,:),'YLabel',[]);
set(ax(:,2:3),'XTickLabel',[]);
set(ax(:,2:3),'XLabel',[]);

for ii = 0:size(ax,2)-1
for jj = 0:size(ax,1)-1
	set(ax(jj+1,ii+1),...
		'Parent',			fh,...
		'Units',			'centimeter',...
		'Position',			[(DIM.padding.left + ii*AXWIDTH) (DIM.padding.bottom + jj*AXHEIGHT) AXWIDTH AXHEIGHT] ...
	);
end
end


fh.UserData.dim = DIM;
fh.UserData.axes = ax;