% load FD scaling
EXPORT = lib.require(@model.tov.fd.scale);


ANCH = lib.require(@model.tov.rar.anchor);
MAP  = lib.require(@model.tov.rar.map);

% SURFACE SCALE
fscale = @(obj,ykey) 1/ANCH.surface.map(obj,ykey);

EXPORT.surface.radius = module.ProfileScaling(...
	@(obj) fscale(obj,'radius'),...
	'r_s'...
);

EXPORT.surface.mass = module.ProfileScaling(...
	@(obj) fscale(obj,MAP.mass),...
	'M_s'...
);

EXPORT.surface.velocity = module.ProfileScaling(...
	@(obj) fscale(obj,MAP.velocity),...
	'v_s'...
);