function cacheAnalysisGrid
P		= load('export/TblAnalysisTheta0Low.mat');

MAP		= lib.require(@model.tov.rar.map);
ANCH	= lib.require(@model.tov.rar.anchor);

% set cache maps
fMap	= @(p) struct(...
	'theta0',	p.data.theta0,...
	'rc',		ANCH.velocity_core.map(p,MAP.radius),...
	'rp',		ANCH.velocity_plateau.map(p,MAP.radius),...
	'rh',		ANCH.velocity_halo.map(p,MAP.radius),...
	'vc',		ANCH.velocity_core.map(p,MAP.velocity),...
	'vp',		ANCH.velocity_plateau.map(p,MAP.velocity),...
	'vh',		ANCH.velocity_halo.map(p,MAP.velocity),...
	'Mc',		ANCH.velocity_core.map(p,MAP.mass),...
	'Mp',		ANCH.velocity_plateau.map(p,MAP.mass),...
	'Mh',		ANCH.velocity_halo.map(p,MAP.mass),...
	'rho0',		ANCH.center.map(p,MAP.density),...
	'rhoc',		ANCH.velocity_core.map(p,MAP.density),...
	'rhop',		ANCH.velocity_plateau.map(p,MAP.density),...
	'rhoh',		ANCH.velocity_halo.map(p,MAP.density),...
	'THETA0',	ANCH.center.map(p,MAP.degeneracy),...
	'THETAc',	ANCH.velocity_core.map(p,MAP.degeneracy),...
	'THETAp',	ANCH.velocity_plateau.map(p,MAP.degeneracy),...
	'THETAh',	ANCH.velocity_halo.map(p,MAP.degeneracy) ...
);

% cache data
T.low	= P.low.map(fMap);
T.trans	= P.trans.map(fMap);
T.high	= P.high.map(fMap);

% save
lib.save('export/CacheAnalysisTheta0Low.mat',T);