function fh = figure()

BETA0LIM	= [1E-6,1E2];
RLIM		= [1E0,1E10];
MLIM		= [1E0,1E9];
DTHETALIM	= [-5,55];

BETA0TICK	= 10.^(-5:2:1);

% axes model
AXMODEL.radius = {...
	'xlabel','$\beta_0$',...
	'ylabel','$r/r_c$',...
	'axes', {...
		'XLim',		BETA0LIM, ...
		'YLim',		RLIM,...
		'XTick',	BETA0TICK,...
		'YTick',	10.^(0:2:10),...
		'XScale',	'log',...
		'YScale',	'log' ...
	}...
};

AXMODEL.mass = {...
	'xlabel', '$\beta_0$',...
	'ylabel', '$M(r)/M_c$',...
	'axes',	{...
		'XLim',		BETA0LIM, ...
		'YLim',		MLIM,...
		'XTick',	BETA0TICK,...
		'YTick',	10.^(0:2:8),...
		'XScale',	'log',...
		'YScale',	'log' ...
	}...
};

AXMODEL.degeneracy = {...
	'xlabel','$\beta_0$',...
	'ylabel','$\theta_0 - \theta(r)$',...
	'axes',{...
		'XLim',		BETA0LIM, ...
		'YLim',		DTHETALIM,...
		'XTick',	BETA0TICK,...
		'YTick',	0:10:50,...
		'XScale',	'log' ...
	}...
};

% create axes grid
for ii=1:3
	ax(:,ii) = [
		model.tov.rar.figure.ax(AXMODEL.degeneracy{:})
		model.tov.rar.figure.ax(AXMODEL.mass{:})
		model.tov.rar.figure.ax(AXMODEL.radius{:})
	];
end

% figure
fh = module.sapthesis.figure_grid(ax,'axHeight','equal','figure',{'FileName','analysis'});