function fh = figure
AXIS.core	= lib.require(@lib.model.tov.rar.axes.core);
AXIS.plat	= lib.require(@lib.model.tov.rar.axes.plateau);
AXIS.halo	= lib.require(@lib.model.tov.rar.axes.halo);

fLABEL.radius = @(AXIS) struct(...
	'format',		'$%s/%s$',...
	'mapmodel',		AXIS.radius.mapmodel,...
	'scalemodel',	AXIS.radius.scalemodel ...
);

fLABEL.density		= '$\rho(r)$';
fLABEL.velocity		= '$v(r)$';
fLABEL.mass			= '$M(r)$';
fLABEL.degeneracy	= '$\theta(r)$';


AX.core.radius = {...
	'XLim',		[1E-2,1E8],...
	'XTick',	10.^(-1:2:7),...
	'XScale',	'log' ...
};

AX.core.density = {...
	'YLim',		[1E-21,1E2],...
	'YTick',	[],...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.core.velocity = {...
	'YLim',		[2E-4,2E0],...
	'YTick',	[],...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.core.mass = {...
	'YLim',		[1E-4,1E8],...
	'YTick',	[],...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.core.degeneracy = {...
	'YLim',		[-95,5],...
	'YTick',	[],...
	'YMinorTick', 'off' ...
};

AX.plat.radius = {...
	'XLim',		[1E-6,1E4],...
	'XTick',	10.^(-5:2:4),...
	'XScale',	'log' ...
};

AX.plat.density = {...
	'YLim',		[1E-8,1E16],...
	'YTick',	[],...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.plat.velocity = {...
	'YLim',		[2E-1,2E3],...
	'YTick',	[],...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.plat.mass = {...
	'YLim',		[1E-4,1E10],...
	'YTick',	[],...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.plat.degeneracy = {...
	'YLim',		[-20,80],...
	'YTick',	[],...
	'YMinorTick', 'off' ...
};

AX.halo.radius = {...
	'XLim',		[1E-8,1E4],...
	'XTick',	10.^(-7:2:5),...
	'XScale',	'log' ...
};

AX.halo.density = {...
	'YLim',		[1E-8,1E22],...
	'YTick',	[],...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.halo.velocity = {...
	'YLim',		[2E-3,2E1],...
	'YTick',	[],...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.halo.mass = {...
	'YLim',		[1E-8,1E4],...
	'YTick',	[],...
	'YScale',	'log'...
	'YMinorTick', 'off' ...
};

AX.halo.degeneracy = {...
	'YLim',		[-20,80],...
	'YTick',	[],...
	'YMinorTick', 'off' ...
};

ax(4,1) = lib.module.figure.axes('x',AXIS.core, 'y',fLABEL.density,		'axes',[AX.core.radius,AX.core.density]);
ax(3,1) = lib.module.figure.axes('x',AXIS.core, 'y',fLABEL.velocity,	'axes',[AX.core.radius,AX.core.velocity]);
ax(2,1) = lib.module.figure.axes('x',AXIS.core, 'y',fLABEL.mass,		'axes',[AX.core.radius,AX.core.mass]);
ax(1,1) = lib.module.figure.axes('x',AXIS.core, 'y',fLABEL.degeneracy,	'axes',[AX.core.radius,AX.core.degeneracy]);

ax(4,2) = lib.module.figure.axes('x',AXIS.plat, 'y',fLABEL.density,		'axes',[AX.plat.radius,AX.plat.density]);
ax(3,2) = lib.module.figure.axes('x',AXIS.plat, 'y',fLABEL.velocity,	'axes',[AX.plat.radius,AX.plat.velocity]);
ax(2,2) = lib.module.figure.axes('x',AXIS.plat, 'y',fLABEL.mass,		'axes',[AX.plat.radius,AX.plat.mass]);
ax(1,2) = lib.module.figure.axes('x',AXIS.plat, 'y',fLABEL.degeneracy,	'axes',[AX.plat.radius,AX.plat.degeneracy]);

ax(4,3) = lib.module.figure.axes('x',AXIS.halo, 'y',fLABEL.density,		'axes',[AX.halo.radius,AX.halo.density]);
ax(3,3) = lib.module.figure.axes('x',AXIS.halo, 'y',fLABEL.velocity,	'axes',[AX.halo.radius,AX.halo.velocity]);
ax(2,3) = lib.module.figure.axes('x',AXIS.halo, 'y',fLABEL.mass,		'axes',[AX.halo.radius,AX.halo.mass]);
ax(1,3) = lib.module.figure.axes('x',AXIS.halo, 'y',fLABEL.degeneracy,	'axes',[AX.halo.radius,AX.halo.degeneracy]);

fh = lib.module.sapthesis.figure_grid(ax,'axHeight','equal');
