function fh = figure
AXIS	= lib.require(@lib.model.tov.rar.axes.raw);

AR			= AXIS.radius;
ARHO		= AXIS.density;
AV			= AXIS.velocity;
AM			= AXIS.mass;


AX.radius = {...
	'XLim',		[5E-1,5E9],...
	'XTick',	10.^(-1:2:9),...
	'XScale',	'log' ...
};

AX.density = {...
	'YLim',		[1E-25,1E-5],...
	'YTick',	10.^(-24:4:0),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.velocity = {...
	'YLim',		[2E-5,2E-2],...
	'YTick',	10.^(-4:1:0),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.mass = {...
	'YLim',		[1E-8,1E4],...
	'YTick',	10.^(-8:3:4),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

for ii=1:1
	ax(3,ii) = lib.module.figure.axes('x',AR, 'y',ARHO,	'axes',[AX.radius,AX.density]);
	ax(2,ii) = lib.module.figure.axes('x',AR, 'y',AV,	'axes',[AX.radius,AX.velocity]);
	ax(1,ii) = lib.module.figure.axes('x',AR, 'y',AM,	'axes',[AX.radius,AX.mass]);
end

fh = lib.module.sapthesis.figure_grid(ax,'axHeight',4);

% link all x axes
linkaxes(ax,'x')
