function fh = figure
AXIS	= lib.require(@model.tov.rar.axes.raw);

AR			= AXIS.radius;
ARHO		= AXIS.density;
AV			= AXIS.velocity;
AM			= AXIS.mass;


AXLABEL.radius = struct(...
	'format',		'$%s\quad[%s]$',...
	'mapmodel',		AR.mapmodel,...
	'scalemodel',	AR.scalemodel ...
);

AXLABEL.density = struct(...
	'format',		'$%s\quad[%s]$',...
	'mapmodel',		ARHO.mapmodel,...
	'scalemodel',	ARHO.scalemodel ...
);

AXLABEL.velocity = struct(...
	'format',		'$%s\quad[%s]$',...
	'mapmodel',		AV.mapmodel,...
	'scalemodel',	AV.scalemodel ...
);

AXLABEL.mass = struct(...
	'format',		'$%s\quad[%s]$',...
	'mapmodel',		AM.mapmodel,...
	'scalemodel',	AM.scalemodel ...
);


AX.radius = {...
	'XLim',		[5E-1,1E7],...
	'XTick',	10.^(-1:7),...
	'XScale',	'log' ...
};

AX.density = {...
	'YLim',		[1E-30,1E-5],...
	'YTick',	10.^(-28:4:0),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.velocity = {...
	'YLim',		[2E-6,2E0],...
	'YTick',	10.^(-5:1:0),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

AX.mass = {...
	'YLim',		[1E-8,1E8],...
	'YTick',	10.^(-8:3:8),...
	'YScale',	'log',...
	'YMinorTick', 'off' ...
};

for ii=1:1
	ax(3,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.density,'axes',[AX.radius,AX.density]);
	ax(2,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.velocity,'axes',[AX.radius,AX.velocity]);
	ax(1,ii) = model.tov.rar.figure.ax('xlabel',AXLABEL.radius,'ylabel',AXLABEL.mass,'axes',[AX.radius,AX.mass]);
end

fh = module.sapthesis.figure_grid(ax,'axHeight',4);

% link all x axes
linkaxes(ax,'x')
