function main
P			= load('export/CacheWithoutCutoffProfilesRho0.mat');
STYLE		= lib.require(@configs.style_profiles);
AXIS.raw	= lib.require(@model.tov.rar.axes.raw);
fh			= view.without_cutoff.rho0.profiles_raw.figure();

% show figure
figure(fh);

% density
axes(fh.UserData.axes(3,1));

hg.thin = hggroup(STYLE.fdgroup{:});
P.thin.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.raw.radius,...
	'y',	AXIS.raw.density,...
	'plot',	[STYLE.fd,{'Parent',hg.thin}] ...
));


% velocity
axes(fh.UserData.axes(2,1));

hg.thin = hggroup(STYLE.fdgroup{:});
P.thin.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.raw.radius,...
	'y',	AXIS.raw.velocity,...
	'plot',	[STYLE.fd,{'Parent',hg.thin}]...
));


% mass
axes(fh.UserData.axes(1,1));

hg.thin = hggroup(STYLE.fdgroup{:});
P.thin.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.raw.radius,...
	'y',	AXIS.raw.mass,...
	'plot',	[STYLE.fd,{'Parent',hg.thin}]...
));

% legend
axes(fh.UserData.axes(1,1));
lib.view.plot.legend([],'location','northwest');

% save
lib.view.latex.figure(...
	'path',		'export/without-cutoff/rho0-profiles-raw/',...
	'figure',	fh,...
	'label',	'fig:profiles:without-cutoff:central-density:raw',...
	'caption',	fileread('+view/+without_cutoff/+rho0/+profiles_raw/caption.txt') ...
);

function vline(x,y,varargin)
lib.view.plot.vline(x,'Color', [1 1 1]*0.7, 'LineStyle',':',varargin{:});
plot(x,y,'Marker','o', 'MarkerFaceColor', 'w', 'MarkerEdgeColor','w','MarkerSize',10);