function fh = figure
RHO0LIM		= [1E-16,1E4];
RLIM		= [1E0,1E10];
MLIM		= [1E-5,1E9];
DTHETALIM	= [-5,85];

% axes
AX.radius = {...
	'xlabel','$\rho_0$',...
	'ylabel','$r$',...
	'axes', {...
		'XLim',		RHO0LIM, ...
		'YLim',		RLIM,...
		'XScale',	'log',...
		'YScale',	'log',...
		'XTick',	10.^(-16:4:4),...
		'YTick',	10.^(0:2:10) ...
	}...
};

AX.mass = {...
	'xlabel', '$\rho_0$',...
	'ylabel', '$M(r)$',...
	'axes',	{...
		'XLim',		RHO0LIM, ...
		'YLim',		MLIM,...
		'XScale',	'log',...
		'YScale',	'log',...
		'YTick',	10.^(0:2:8) ...
	}...
};

AX.degeneracy = {...
	'xlabel','$\rho_0$',...
	'ylabel','$\theta_0 - \theta(r)$',...
	'axes',{...
		'XLim',		RHO0LIM, ...
		'YLim',		DTHETALIM,...
		'XScale',	'log',...
		'YTick',	-15:15:80 ...
	}...
};


for ii=1:3
	ax(:,ii) = [
		model.tov.rar.figure.ax(AX.degeneracy{:})
		model.tov.rar.figure.ax(AX.mass{:})
		model.tov.rar.figure.ax(AX.radius{:})
	];
end

fh = module.sapthesis.figure_grid(ax,'axHeight',@(w) w,'figure',{'FileName','analysis-rho0'});