EXPORT.tight =  module.ProfileClip(...
	@(obj,Y) min(Y),...
	@(obj,Y) max(Y),...
	0,...
	0,...
	0 ...
);

EXPORT.padding5 =  module.ProfileClip(...
	@(obj,Y) min(Y),...
	@(obj,Y) max(Y),...
	0.05,...
	0.05,...
	0 ...
);

EXPORT.padding10 =  module.ProfileClip(...
	@(obj,Y) min(Y),...
	@(obj,Y) max(Y),...
	0.1,...
	0.1,...
	0 ...
);