function main
P			= load('export/CacheProfileTheta0Low.mat');
STYLE		= lib.require(@configs.style_profiles);
ANCH		= lib.require(@model.tov.rar.anchor);
AXIS.raw	= lib.require(@model.tov.rar.axes.raw);
AXIS.center	= lib.require(@model.tov.rar.axes.center);
AXIS.core	= lib.require(@model.tov.rar.axes.core);
fh			= view.without_cutoff.theta0.profiles_core.figure();

% define fully degenerate core and pointlike vacuum solution
opts = struct('xmax', 1E20, 'tau', 1E-16, 'rtau', 1E-8);
pFDG = model.tov.core.profile('fermi_energy', 1 + 1E-6*50).calc(opts);
pFDG.data.density(end) = realmin;

pPL = model.elementary.pointlike.profile(ANCH.surface.map(pFDG,AXIS.raw.mass));
pPL.set('radius',logspace(log10(pFDG.data.radius(end)),log10(pFDG.data.radius(end)) + 10));

% set axis for pointlike solution (core focus)
MAP.pl = lib.require(@model.tov.pointlike.map);
AXIS.pointlike.core.radius		= module.ProfileAxis(MAP.pl.radius,		@(obj) AXIS.core.radius.scalemodel.map(pFDG));
AXIS.pointlike.core.velocity	= module.ProfileAxis(MAP.pl.velocity,	@(obj) AXIS.core.velocity.scalemodel.map(pFDG));
AXIS.pointlike.core.mass		= module.ProfileAxis(MAP.pl.mass,		@(obj) AXIS.core.mass.scalemodel.map(pFDG));

% show figure
figure(fh);

% density
axes(fh.UserData.axes(3,1));
hg.fgdgroup = hggroup(STYLE.fdggroup{:});
vline(1,ANCH.velocity_core.map(pFDG,AXIS.center.density),'Parent',hg.fgdgroup);

lib.view.plot.curve2D(...
	'data', pFDG,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot', [STYLE.fdg,{'Parent',hg.fgdgroup}]...
);

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.center.density,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}] ...
));

lib.view.plot.legend([],'location','northeast');


% velocity
axes(fh.UserData.axes(2,1));
vline(1,1);

hg.fgdgroup = hggroup(STYLE.fdggroup{:});
lib.view.plot.curve2D(...
	'data', pPL,...
	'x',	AXIS.pointlike.core.radius,...
	'y',	AXIS.pointlike.core.velocity,...
	'plot', [STYLE.fdg,{'Parent',hg.fgdgroup}] ...
);

lib.view.plot.curve2D(...
	'data', pFDG,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot',	[STYLE.fdg,{'Parent',hg.fgdgroup}]...
);

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.velocity,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));


% mass
axes(fh.UserData.axes(1,1));
vline(1,1);

hg.fgdgroup = hggroup(STYLE.fdggroup{:});
lib.view.plot.curve2D(...
	'data', pPL,...
	'x',	AXIS.pointlike.core.radius,...
	'y',	AXIS.pointlike.core.mass,...
	'plot',	[STYLE.fdg,{'Parent',hg.fgdgroup}]...
);
lib.view.plot.curve2D(...
	'data', pFDG,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot',	[STYLE.fdg,{'Parent',hg.fgdgroup}]...
);

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.core.radius,...
	'y',	AXIS.core.mass,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));


% save
lib.view.latex.figure(...
	'path',		'export/without-cutoff/theta0-profiles-core/',...
	'figure',	fh,...
	'label',	'fig:profiles:without-cutoff:central-degeneracy:core',...
	'caption',	fileread('+view/+without_cutoff/+theta0/+profiles_core/caption.txt') ...
);

function vline(x,y,varargin)
lib.view.plot.vline(x,'Color', [1 1 1]*0.7, 'LineStyle',':',varargin{:});
plot(x,y,'Marker','o', 'MarkerFaceColor', 'w', 'MarkerEdgeColor','w','MarkerSize',10);