function fh = figure
THETA0LIM	= [-20,50];
RLIM		= [1E0,1E10];
MLIM		= [1E-4,1E6];
DTHETALIM	= [-5,85];

% axes
AX.radius = {...
	'xlabel','$\theta_0$',...
	'ylabel','$r/R$',...
	'axes', {...
		'XLim',		THETA0LIM, ...
		'YLim',		RLIM,...
		'YTick',	10.^(0:2:10),...
		'YScale',	'log' ...
	}...
};

AX.mass = {...
	'xlabel', '$\theta_0$',...
	'ylabel', '$M(r)/M$',...
	'axes',	{...
		'XLim',		THETA0LIM, ...
		'YLim',		MLIM,...
		'YTick',	10.^(-3:2:5),...
		'YScale',	'log' ...
	}...
};

AX.degeneracy = {...
	'xlabel','$\theta_0$',...
	'ylabel','$\theta_0 - \theta(r)$',...
	'axes',{...
		'XLim',		THETA0LIM, ...
		'YLim',		DTHETALIM,...
		'XTick',	-10:10:70,...
		'YTick',	-15:15:80 ...
	}...
};


for ii=1:1
	ax(:,ii) = [
		model.tov.rar.figure.ax(AX.degeneracy{:})
		model.tov.rar.figure.ax(AX.mass{:})
		model.tov.rar.figure.ax(AX.radius{:})
	];
end

fh = module.sapthesis.figure_grid(ax,'axHeight',4);