function main
P			= load('export/CacheProfileTheta0Low.mat');
STYLE		= lib.require(@configs.style_profiles);
ANCH		= lib.require(@lib.model.tov.rar.anchor);
AXIS.plat	= lib.require(@lib.model.tov.rar.axes.plateau);
fh			= view.without_cutoff.theta0.profiles_plateau.figure();

figure(fh);

% density
axes(fh.UserData.axes(3,1));
vline(1,1);

hg.is = hggroup(STYLE.isgroup{:});
plot([realmin,ANCH.center.map(P.is,AXIS.plat.radius)],[1,1]*ANCH.center.map(P.is,AXIS.plat.density),STYLE.is{:},'Parent',hg.is);
lib.view.plot.curve2D(...
	'data', P.is,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.density,...
	'plot',	[STYLE.is,{'Parent',hg.is}]...
);

hg.trans = hggroup(STYLE.transgroup{:});
P.trans.forEach(@(p)lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.density,...
	'plot',	[STYLE.trans,{'Parent',hg.trans}]...
));

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p)lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.density,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));

lib.view.plot.legend([],'location','northeast');

% velocity
axes(fh.UserData.axes(2,1));
vline(1,1);

hg.is = hggroup(STYLE.isgroup{:});
lib.view.plot.curve2D(...
	'data', P.is,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.velocity,...
	'plot', [STYLE.is,{'Parent',hg.is}]...
);

hg.trans = hggroup(STYLE.transgroup{:});
P.trans.forEach(@(p)lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.velocity,...
	'plot',	[STYLE.trans,{'Parent',hg.trans}]...
));

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.velocity,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));

% mass
axes(fh.UserData.axes(1,1));
vline(1,1);

hg.is = hggroup(STYLE.isgroup{:});
lib.view.plot.curve2D(...
	'data', P.is,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.mass,...
	'plot',	[STYLE.is,{'Parent',hg.is}]...
);

hg.trans = hggroup(STYLE.transgroup{:});
P.trans.forEach(@(p)lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.mass,...
	'plot',	[STYLE.trans,{'Parent',hg.trans}]...
));

hg.cored = hggroup(STYLE.fdgroup{:});
P.cored.forEach(@(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.plat.radius,...
	'y',	AXIS.plat.mass,...
	'plot',	[STYLE.fd,{'Parent',hg.cored}]...
));


% save
lib.view.latex.figure(...
	'path',		'export/without-cutoff/theta0-profiles-plateau/',...
	'figure',	fh,...
	'label',	'fig:profiles:without-cutoff:central-degeneracy:plateau',...
	'caption',	fileread('+view/+without_cutoff/+theta0/+profiles_plateau/caption.txt') ...
);

function vline(x,y)
lib.view.plot.vline(x,'Color', [1 1 1]*0.7, 'LineStyle',':');
plot(x,y,'Marker','o', 'MarkerFaceColor', 'w', 'MarkerEdgeColor','w','MarkerSize',10);