function fh=figure_1x1(ax,varargin)

DIM = struct(...
	'width',	11.1125*4/3,...
	'height',	11.1125,...
	'padding',	struct('top', 0.5, 'left', 1.5, 'right', 1.5, 'bottom', 1.5),...
	'grid',		[1,1] ...
);

fh = figure(...
	'Visible',					'off',...
	'defaulttextinterpreter',	'latex',...
	'Units',					'centimeters',...
	'PaperUnits',				'centimeters',...
	'PaperSize',				[DIM.width DIM.height],...
	'PaperPosition',			[0,0,DIM.width,DIM.height],...
	varargin{:}...
);

fh.Position(2) = fh.Position(2) - (DIM.height - fh.Position(4));
fh.Position(3) = DIM.width;
fh.Position(4) = DIM.height;

AXWIDTH		= (DIM.width - (DIM.padding.left + DIM.padding.right))/DIM.grid(2);
AXHEIGHT	= (DIM.height - (DIM.padding.bottom + DIM.padding.top))/DIM.grid(1);

set(ax,...
	'Parent',			fh,...
	'Units',			'centimeter',...
	'Position',			[DIM.padding.left DIM.padding.bottom AXWIDTH AXHEIGHT] ...
);

fh.UserData.dim = DIM;
fh.UserData.axes = ax;