function createProfileGrid
searchCfg = lib.require(@configs.solutionSearchConfig);

% set seed model struct
opts		= struct('xmax', 1E20, 'tau', 1E-16, 'rtau', 1E-4);
param.seed	= struct('theta0', 30, 'W0', 200);
vm.seed		= struct('param', param.seed, 'options', opts);

% set golden section search options
goOpts		= struct('tau',1E-12,'rtau',1E-8,'MaxIter',50);

% nlinfit options cascade
nlOpts				= statset('nlinfit');
nlOpts.FunValCheck	= 'off';
nlOpts.MaxIter		= 50;

% find transition point
[p.trans,vm.trans] = script.gosect.beta0(...
	'model',	vm.seed,...
	'list',		module.ProfileResponse(searchCfg.ResponseList.log_rhop_rho0,'max'),...
	'interval',	[1E-4,1E1],...
	'gosect',	{'options',goOpts} ...
);

%
vm.low	= lib.struct.setfield(vm.seed,'param/beta0', 1E-6);
p.low	= model.tov.rar.profile('model', vm.low);

vm.high	= lib.struct.setfield(vm.seed,'param/beta0', 1E2);
p.high	= model.tov.rar.profile('model', vm.high);


% low temperature with degenerate core
T.low = vm.low;

% temperature transition with degenerate core
grid = linspace(...
	searchCfg.ResponseList.log_rhop_rho0(p.trans),...
	searchCfg.ResponseList.log_rhop_rho0(p.low),...
	21 ...
);

T.trans = script.createGrid(...
	'key',			'log_rhop_rho0',...
	'grid',			grid,...
	'model',		vm.trans,...
	'fSearch',		@script.beta0.findSolution,...
	'search',		{'nlinfit', {'options', nlOpts}} ...
);


% high temperature with degenerate core
grid = linspace(...
	searchCfg.ResponseList.log_rhop_rho0(p.high),...
	searchCfg.ResponseList.log_rhop_rho0(p.trans),...
	21 ...
);

T.high = script.createGrid(...
	'key',			'log_rhop_rho0',...
	'grid',			grid,...
	'model',		vm.high,...
	'fSearch',		@script.beta0.findSolution,...
	'search',		{'nlinfit', {'options', nlOpts}} ...
);

lib.save('export/TblWithoutCutoffBeta0Profiles.mat',T)