lib.module.constraints

% RAW
EXPORT.raw.radius			= lib.module.ProfileMapping(1,'R');
EXPORT.raw.radiusInverse	= lib.module.ProfileMapping(1,'1/R');
EXPORT.raw.mass				= lib.module.ProfileMapping(1,'M');
EXPORT.raw.massDiff			= lib.module.ProfileMapping(1,'M/R');
EXPORT.raw.velocity			= lib.module.ProfileMapping(1,'c');
EXPORT.raw.acceleration		= lib.module.ProfileMapping(1,'c^2/R');


% SI
EXPORT.SI.radius = lib.module.ProfileMapping(...
	@(obj) obj.data.R,...
	'\mathrm{m}' ...
);

EXPORT.SI.mass = lib.module.ProfileMapping(...
	@(obj) obj.data.M,...
	'\mathrm{kg}'...
);

EXPORT.SI.velocity = lib.module.ProfileMapping(...
	c,...
	'\mathrm{m/s}'...
);

EXPORT.SI.acceleration = lib.module.ProfileMapping(...
	@(obj) c^2/obj.data.R,...
	'\mathrm{m/s^2}'...
);


% ASTRO
EXPORT.astro.radius = lib.module.ProfileMapping(...
	@(obj) EXPORT.SI.radius.map(obj)/parsec,...
	'\mathrm{pc}' ...
);

EXPORT.astro.radius_kpc = lib.module.ProfileMapping(...
	@(obj) EXPORT.SI.radius.map(obj)/kpc,...
	'\mathrm{kpc}' ...
);

EXPORT.astro.velocity = lib.module.ProfileMapping(...
	c/1E3,...
	'\mathrm{km/s}'...
);

EXPORT.astro.mass = lib.module.ProfileMapping(...
	@(obj) obj.data.M/Msun,...
	'M_\odot'...
);

EXPORT.astro.massDiff = lib.module.ProfileMapping(...
	@(obj) obj.data.M/Msun/(obj.data.R/parsec),...
	'M_\odot/\mathrm{pc}'...
);