function fh = figure
AXIS.theta0 = {...
	'YLim',		[10,30],...
	'YTick',	15:3:28,...
	'YAxisLocation', 'right' ...
};

AXIS.rho0 = {...
	'YLim',		[1E-20,1E-5],...
	'YTick',	10.^(-22:5:2),...
	'YScale',	'log',...
	'YAxisLocation', 'right' ...
};

AXIS.beta0 = {...
	'YLim',		[3E-7,2E-6]*1E6,...
	'YTick',	[0.4 0.7 1.0 1.5],...
	'YScale',	'log',...
	'YAxisLocation', 'right' ...
};

AXIS.W0 = {...
	'XLim',		[21.6,80],...
	'XTick',	25:10:75 ...
};

AXIS.radius = {...
	'YLim',		[1E0,1E12],...
	'YTick',	10.^(1:2:13),...
	'YScale',	'log' ...
};

AXIS.mass = {...
	'YLim',		[1E-4,1E5],...
	'YTick',	10.^(-3:2:5),...
	'YScale',	'log' ...
};

AXIS.degeneracy = {...
	'YLim',		[-5,80],...
	'YTick',	-15:15:80 ...
};

% axes
AX.radius = {...
	'x','$W_0$',...
	'y','$r/R$',...
	'axes', {...
		AXIS.W0{:},...
		AXIS.radius{:} ...
	}...
};

AX.mass = {...
	'x', '$W_0$',...
	'y', '$M(r)/M$',...
	'axes',	{...
		AXIS.W0{:},...
		AXIS.mass{:} ...
	}...
};

AX.degeneracy = {...
	'x','$W_0$',...
	'y','$\theta_0 - \theta(r)$',...
	'axes',{...
		AXIS.W0{:},...
		AXIS.degeneracy{:} ...
	}...
};

AX.rho0 = {...
	'x','$W_0$',...
	'y','$\rho_0/\rho$',...
	'axes',{...
		AXIS.W0{:},...
		AXIS.rho0{:} ...
	}...
};

AX.beta0 = {...
	'x','$W_0$',...
	'y','$\beta_0 \times 10^{-6}$',...
	'axes',{...
		AXIS.W0{:},...
		AXIS.beta0{:} ...
	}...
};

AX.theta0 = {...
	'x','$W_0$',...
	'y','$\theta_0$',...
	'axes',{...
		AXIS.W0{:},...
		AXIS.theta0{:} ...
	}...
};



ax(1:3,1) = [
	lib.module.figure.axes(AX.degeneracy{:})
	lib.module.figure.axes(AX.mass{:})
	lib.module.figure.axes(AX.radius{:})
];


ax(1:3,2) = [
	lib.module.figure.axes(AX.rho0{:})
	lib.module.figure.axes(AX.beta0{:})
	lib.module.figure.axes(AX.theta0{:})
];

% hide labels manual
set([ax(2:3,1);ax(2:3,2)],'XTickLabel',[]);
set([ax(2:3,1);ax(2:3,2)],'XLabel',[]);

fh = lib.module.sapthesis.figure_grid(ax,...
	'axHeight',		4,...
	'padding',		struct('top', 0.6, 'left', 1.5, 'right', 1.5, 'bottom', 1.5),...
	'showLabels',	'manual' ...
);